version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.13
    working_directory: ~/repo
    steps:
      - checkout
workflows:
  version: 2
  build:
    jobs:
      - build:
          filter:
            branches:
              only:
                - master
