version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.13
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build
          command: |
            GOOS=darwin GOARCH=amd64 go build -o bin/darwin_amd64/terraform-provider-candidaws_v0.0.0
            GOOS=linux GOARCH=amd64 go build -o bin/linux_amd64/terraform-provider-candidaws_v0.0.0
          working_directory: ~/repo
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
